server:
  port:8080
---
spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/weatherReporting
    username: root
    password: MyMail@123
  jpa:
    hibernate.ddl-auto: none
    show_sql: false